### ISSUE TITLE
Seleccion  de repositorio

### ISSUE THREAD

**Issue by teamc3-sys** [teamc3-sys/semillero-devops-nttdata#7]
Entregable: Especificar el repositorio a utilizar

**Comment by teamc3-sys** [comment]
Se realizo una reunion con el grupo de trabajo y se decide la eleccion de GitHub como repositorio.

**Comment by ramisistemas** [comment]
![Image](https://user-images.githubusercontent.com/20059814/213476341-efb6e9c2-aed0-43a0-b6ab-4bc6b1b3e2de.png)



![Image](https://user-images.githubusercontent.com/20059814/213476404-aa8a28b5-b496-4184-b62e-b7e91a52fcca.png)
